config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  resources :forms, only: [:new, :create, :edit, :destroy] do
    post 'update', to: 'forms#update'

    # Twilio
    get 'twilio', to: 'twilio_responses#new'
    post 'twilio/start', to: 'twilio_responses#start'
    post 'twilio/receive', to: 'twilio_responses#receive'

    # Desktop
    get 'desktop', to: 'desktop_responses#new'
    get 'desktop/receive', to: 'desktop_responses#receive'
  end
end

app/views/pages/home.html.erb
<div class="row new-button">
  <%= link_to new_form_path do %>
    <div class="new right columns small-5 medium-5 large-2">
      <span>New Survey</span>
    </div>
  <% end %>
</div>

<!--   CURRENT   -->
<div class="row home-header">
  <h5 class="survey-heading">CURRENT SURVEYS</h5>
</div>

<div class="current">
  <% @forms.each do |f| %>
    <div class="row survey-tile">
      <div class="columns">
        <%= link_to(edit_form_path(f.id)) do %>
          <div class="columns small-7 large-7">
            <h2><%= f.name %></h2>
          </div>
        <% end %>
        <div class="columns right small-5 large-5">
          <%= link_to(form_path(f.id), method: :delete) do %>
            <div class="delete right">
              <i class="fa fa-trash fa-lg"></i>
            </div>
          <% end %>
          <%= link_to(form_twilio_path(f.id), class: 'delete right') do %>
            <i class="fa fa-send fa-lg"></i>
          <% end %>
          <%= link_to(form_desktop_path(f.id)) do %>
            <div class="delete right">
              <i class="fa fa-desktop fa-lg"></i>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<!--   SENT   -->
<div class="row home-header">
  <h5 class="survey-heading">SENT SURVEYS</h5>
</div>

<div class="sent"></div>