config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  resources :forms, only: [:new, :create, :edit, :destroy] do
    post 'update', to: 'forms#update'

    # Twilio
    get 'twilio', to: 'twilio_responses#new'
    post 'twilio/start', to: 'twilio_responses#start'
    post 'twilio/receive', to: 'twilio_responses#receive'

    # Desktop
    get 'desktop', to: 'desktop_responses#new'
    get 'desktop/receive', to: 'desktop_responses#receive'
  end
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  def new
  end

  def create
    form = Form.new(name: params["name"], intro: params["intro"], json: params.to_json)
    if form.save
      render_json_message(:ok, message: 'Form created!', data: { save_path: form_update_path(form.id), edit_path: edit_form_path(form.id) })
    else
      render_json_message(:forbidden, errors: form.errors.full_messages)
    end
  end

  def edit
    # return json
    @form = Form.find(params[:id])
  end

  def update
    # save json
    form = Form.find(params[:form_id])
    if form.update(name: params["name"], intro: params["intro"], json: params.to_json)
      render_json_message(:ok, message: "Form saved!")
    else
      render_json_message(:forbidden, errors: form.errors.full_messages)
    end
  end

  def destroy
    form = Form.find(params[:id])
    if form.destroy
      redirect_to(root_path)
    else
      render_json_message(:forbidden, errors: form.errors.full_messages)
    end
  end
end

app/views/forms/edit.html.erb
<%= react_component('FormCreate', root_path: root_path, save_path: form_update_path(@form.id), initial_state: @form.json) %>

app/views/forms/new.html.erb
<!-- need to change ids and paths when controller gets updated -->
<%= react_component('FormCreate', root_path: root_path, save_path: forms_path) %>

app/views/forms/twilio.html.erb
<div class="row home-header">
  <h5 class="survey-heading">CHOOSE RECEPIENTS</h5>
</div>

<form>
  <div class="row">
    <h1 id="form-name" data-fid="<%= @f.id %>"><%= @f.name %></h1>
    <p>Phone Numbers, separated by commas.</p>
    <textarea rows="6" cols="1" placeholder="Phone Numbers" id="phonenumbers"></textarea>
  </div>

  <div class="row finish-cancel">
    <div class="finish columns right small-5 medium-3 large-2" id="send-twilio-num">
      <span>Send</span>
    </div>
    <%= link_to(root_path) do %>
      <div class = "cancel columns right small-6 medium-4 large-3">
        <span>Return to Dashboard</span>
      </div>
    <% end %>
  </div>
</form>